eureka:
  client:
    register-with-eureka: true #this will go and connect with service registry
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
